import { create } from 'zustand'
import { persist } from 'zustand/middleware'

interface ThemeState {
  primaryColor: string
  orgName: string
  orgLogo: string | null
  reportFooter: string
  setPrimaryColor: (color: string) => void
  setOrgName: (name: string) => void
  setOrgLogo: (logo: string | null) => void
  setReportFooter: (text: string) => void
}

export const useThemeStore = create<ThemeState>()(
  persist(
    (set) => ({
      primaryColor: '#2563eb', // Default Blue
      orgName: 'Prophet Intelligence',
      orgLogo: null,
      reportFooter: 'Generated by Prophet AI Strategic Advisor',
      setPrimaryColor: (color) => set({ primaryColor: color }),
      setOrgName: (name) => set({ orgName: name }),
      setOrgLogo: (logo) => set({ orgLogo: logo }),
      setReportFooter: (text) => set({ reportFooter: text }),
    }),
    {
      name: 'prophet-theme-storage',
    }
  )
)
